### ISSUE TITLE
defaultChannel issue

### ISSUE THREAD

**Issue by Vimppura69** [masagameplay/MaSuiteChat#21]
Because Masuitechat has a defaultChannel defined in every server, it automatically changes user's chat channel when moving from one server to another. This often causes unwanted consequence ex. when staff channel is used as a sensitive communication channel. Suddenly the channel changes to global (our default) via server changes and every player can see the next sensitive message. 

Is there a way now or in the future to have the defaultChannel as a first-time-channel BUT not as a forced one when moving from server to server?

**Comment by Jadiction** [comment]
I added something in my PR that will pretty much do just this except their channel will still become the defaultChannel on player rejoins (and server restarts).
