### ISSUE TITLE
Don't work with FastLogin

### ISSUE THREAD

**Issue by s99889989** [masagameplay/MaSuiteChat#4]
10:16:03 [資訊] Using standard Java JCE cipher.
10:16:03 [資訊] Using standard Java compressor.
10:16:03 [資訊] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355
10:16:03 [資訊] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
10:16:03 [資訊] Loaded plugin LiteAnnouncer version 6.3.1 by LITEFINE
10:16:03 [資訊] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin SkinsRestorer version 13.3 by Th3Tr0LLeR
10:16:03 [資訊] Loaded plugin MaSuiteCore version 1.4.2 by Masagameplay
10:16:03 [資訊] Loaded plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
10:16:03 [資訊] Loaded plugin DeluxeChatBungee version 1.13.1 by extended_clip
10:16:03 [資訊] Loaded plugin SpongePls version 1.1-SNAPSHOT-b#35 by Cory Redmond
10:16:03 [資訊] Loaded plugin BungeeSystem version 1.1.0.3 by OpException
10:16:03 [資訊] Loaded plugin MaSuiteTeleports version 1.2.1 by Masagameplay
10:16:03 [資訊] Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin BungeeKick version 1.2 by Vik1395
10:16:03 [資訊] Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Loaded plugin BungeeTabListPlus version 2.8.9 by CodeCrafter47
10:16:03 [警告] Forced host server pvp is not defined
10:16:03 [警告] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
10:16:03 [資訊] [LiteAnnouncer] Plugin enabled. Version: 6.3.1. Made by LITEFINE.
10:16:03 [資訊] Enabled plugin LiteAnnouncer version 6.3.1 by LITEFINE
10:16:03 [資訊] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:03 [資訊] Enabled plugin SkinsRestorer version 13.3 by Th3Tr0LLeR
10:16:03 [警告] Exception encountered when loading plugin: MaSuiteCore
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
	at fi.matiaspaavilainen.masuitecore.database.Database.connect(Database.java:16)
	at fi.matiaspaavilainen.masuitecore.MaSuiteCore.onEnable(MaSuiteCore.java:22)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:16:04 [嚴重] 九月 17, 2018 10:16:04 上午 com.zaxxer.hikari.HikariDataSource <init>
資訊: HikariPool-1 - Starting...

10:16:04 [嚴重] 九月 17, 2018 10:16:04 上午 com.zaxxer.hikari.HikariDataSource <init>
資訊: HikariPool-1 - Start completed.

10:16:04 [資訊] Enabled plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
10:16:04 [資訊] Enabled plugin DeluxeChatBungee version 1.13.1 by extended_clip
10:16:04 [資訊] Enabled plugin SpongePls version 1.1-SNAPSHOT-b#35 by Cory Redmond
10:16:04 [資訊] [BungeeSystem] v.1.1.0.3 successfully enabled!
10:16:04 [資訊] Enabled plugin BungeeSystem version 1.1.0.3 by OpException
10:16:04 [警告] Exception encountered when loading plugin: MaSuiteTeleports
java.lang.NullPointerException
	at fi.matiaspaavilainen.masuitecore.database.Database.createTable(Database.java:35)
	at fi.matiaspaavilainen.masuiteteleports.MaSuiteTeleports.onEnable(MaSuiteTeleports.java:37)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:16:04 [資訊] Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:04 [資訊] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:04 [資訊] Enabled plugin BungeeKick version 1.2 by Vik1395
10:16:04 [資訊] Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:04 [資訊] Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:04 [資訊] Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:04 [資訊] [BungeeTabListPlus] Starting UpdateChecker Task
10:16:04 [資訊] [BungeeTabListPlus] Loading default.yml
10:16:04 [資訊] Enabled plugin BungeeTabListPlus version 2.8.9 by CodeCrafter47
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a    +===============+
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a    | SkinsRestorer |
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a    +===============+
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §b    Current version: §a13.3
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a    This is the latest version!
10:16:04 [資訊] §f§e[§2SkinsRestorer§e] §a----------------------------------------------
10:16:05 [資訊] Listening on /0.0.0.0:25565
10:16:58 [資訊] Using standard Java JCE cipher.
10:16:58 [資訊] Using standard Java compressor.
10:16:58 [資訊] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355
10:16:58 [資訊] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
10:16:58 [資訊] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Loaded plugin MaSuiteCore version 1.4.2 by Masagameplay
10:16:58 [資訊] Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Loaded plugin MaSuiteTeleports version 1.2.1 by Masagameplay
10:16:58 [資訊] Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [警告] Forced host server pvp is not defined
10:16:58 [警告] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
10:16:58 [資訊] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [嚴重] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10:16:58 [嚴重] SLF4J: Defaulting to no-operation (NOP) logger implementation
10:16:58 [嚴重] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10:16:58 [資訊] Enabled plugin MaSuiteCore version 1.4.2 by Masagameplay
10:16:58 [資訊] Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Enabled plugin MaSuiteTeleports version 1.2.1 by Masagameplay
10:16:58 [資訊] Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:16:58 [資訊] Listening on /0.0.0.0:25565
10:18:01 [資訊] Using standard Java JCE cipher.
10:18:01 [資訊] Using standard Java compressor.
10:18:01 [資訊] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355
10:18:01 [資訊] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
10:18:01 [資訊] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Loaded plugin MaSuiteCore version 1.4.2 by Masagameplay
10:18:01 [資訊] Loaded plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
10:18:01 [資訊] Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Loaded plugin MaSuiteTeleports version 1.2.1 by Masagameplay
10:18:01 [資訊] Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [警告] Forced host server pvp is not defined
10:18:01 [警告] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
10:18:01 [資訊] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [警告] Exception encountered when loading plugin: MaSuiteCore
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51)
	at fi.matiaspaavilainen.masuitecore.database.Database.connect(Database.java:16)
	at fi.matiaspaavilainen.masuitecore.MaSuiteCore.onEnable(MaSuiteCore.java:22)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:18:01 [嚴重] 九月 17, 2018 10:18:01 上午 com.zaxxer.hikari.HikariDataSource <init>
資訊: HikariPool-1 - Starting...

10:18:01 [嚴重] 九月 17, 2018 10:18:01 上午 com.zaxxer.hikari.HikariDataSource <init>
資訊: HikariPool-1 - Start completed.

10:18:01 [資訊] Enabled plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
10:18:01 [資訊] Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [警告] Exception encountered when loading plugin: MaSuiteTeleports
java.lang.NullPointerException
	at fi.matiaspaavilainen.masuitecore.database.Database.createTable(Database.java:35)
	at fi.matiaspaavilainen.masuiteteleports.MaSuiteTeleports.onEnable(MaSuiteTeleports.java:37)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:18:01 [資訊] Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
10:18:01 [資訊] Listening on /0.0.0.0:25565

**Comment by masagameplay** [comment]
Thanks for posting this. I think that you didn't put your MySQL information to plugins/MaSuite/config.yml, regarding some lines tell that failed to creating MaSuiteTeleports' table.

**Comment by s99889989** [comment]
Thank you for your reply, I am sorry that I sent the wrong place.
When I remove the FastLogin plugins, MaSuite is working fine.
This is the case without the FastLogin plugins.

00:18:25 [資訊] Using standard Java JCE cipher.
00:18:25 [資訊] Using standard Java compressor.
00:18:25 [資訊] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:ba07397:1355
00:18:25 [資訊] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
00:18:25 [資訊] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Loaded plugin MaSuiteCore version 1.4.2 by Masagameplay
00:18:25 [資訊] Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Loaded plugin MaSuiteTeleports version 1.2.1 by Masagameplay
00:18:25 [資訊] Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [警告] Forced host server pvp is not defined
00:18:25 [警告] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
00:18:25 [資訊] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [嚴重] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
00:18:25 [嚴重] SLF4J: Defaulting to no-operation (NOP) logger implementation
00:18:25 [嚴重] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
00:18:25 [資訊] Enabled plugin MaSuiteCore version 1.4.2 by Masagameplay
00:18:25 [資訊] Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Enabled plugin MaSuiteTeleports version 1.2.1 by Masagameplay
00:18:25 [資訊] Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:ba07397:1355 by SpigotMC
00:18:25 [資訊] Listening on /0.0.0.0:25565

**Comment by masagameplay** [comment]
This issue is fixed in https://github.com/masagameplay/MaSuiteCore/commit/c07da8333bdd4a14a27f66a65ea02b6543340dcc
